### ISSUE TITLE
web site shows invalid username for password

### ISSUE THREAD

**Issue by AvdN** [Anaconda-Server/support#24]
After logging out and trying to login again on the website, I got

![anaconda_username_username](https://cloud.githubusercontent.com/assets/1210650/13453563/6882deea-e051-11e5-95ba-bd251b4b092e.png)

The browser pasted in the email as default (which is what it proposed to save), which is a minor nuisance. But he invalid username on the second box, is a bit confusing. I realise you cannot check
the password if you don't know the user, but this way it looks like you have to type the username twice. (The password was correct in this case, I only had to change my email to my user name).

**Comment by stephenakearns** [comment]
Hi @mistakevin - can you take care of this issue?

**Comment by srossross** [comment]
This looks like it is already fixed in develop. This will make it into the release this week.

**Comment by dsludwig** [comment]
<img width="897" alt="screen shot 2016-04-04 at 9 22 05 am" src="https://cloud.githubusercontent.com/assets/787031/14254930/bd42a604-fa46-11e5-9d7e-0463944fe1e2.png">

This is not fixed yet, as far as I can tell.

**Comment by srossross** [comment]
Ah thanks you are correct, I tried to reproduce with only an invalid password and got the correct error message:
![image](https://cloud.githubusercontent.com/assets/741611/14255028/22f35a48-fa47-11e5-979e-1766546cb54e.png)
